# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spring_flood_design.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1807, 853)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 661, 670))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 270, 660, 401))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.table_stvor1 = QtWidgets.QTableWidget(self.tab)
        self.table_stvor1.setGeometry(QtCore.QRect(0, 0, 661, 371))
        self.table_stvor1.setObjectName("table_stvor1")
        self.table_stvor1.setColumnCount(3)
        self.table_stvor1.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stvor1.setItem(8, 1, item)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.table_stvor2 = QtWidgets.QTableView(self.tab_3)
        self.table_stvor2.setGeometry(QtCore.QRect(0, 0, 661, 381))
        self.table_stvor2.setAlternatingRowColors(True)
        self.table_stvor2.setObjectName("table_stvor2")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.label_zone_2 = QtWidgets.QLabel(self.frame)
        self.label_zone_2.setGeometry(QtCore.QRect(10, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_zone_2.setFont(font)
        self.label_zone_2.setObjectName("label_zone_2")
        self.spin_h = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_h.setGeometry(QtCore.QRect(312, 15, 62, 22))
        self.spin_h.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_h.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_h.setMaximum(150.0)
        self.spin_h.setProperty("value", 80.0)
        self.spin_h.setObjectName("spin_h")
        self.label_zone_5 = QtWidgets.QLabel(self.frame)
        self.label_zone_5.setGeometry(QtCore.QRect(380, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_zone_5.setFont(font)
        self.label_zone_5.setObjectName("label_zone_5")
        self.label_zone = QtWidgets.QLabel(self.frame)
        self.label_zone.setGeometry(QtCore.QRect(10, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_zone.setFont(font)
        self.label_zone.setObjectName("label_zone")
        self.comboBox_zone = QtWidgets.QComboBox(self.frame)
        self.comboBox_zone.setGeometry(QtCore.QRect(130, 46, 141, 22))
        self.comboBox_zone.setObjectName("comboBox_zone")
        self.comboBox_zone.addItem("")
        self.comboBox_zone.addItem("")
        self.label_zone_3 = QtWidgets.QLabel(self.frame)
        self.label_zone_3.setGeometry(QtCore.QRect(280, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_zone_3.setFont(font)
        self.label_zone_3.setObjectName("label_zone_3")
        self.spin_cv = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_cv.setGeometry(QtCore.QRect(452, 46, 62, 22))
        self.spin_cv.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_cv.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_cv.setMinimum(0.01)
        self.spin_cv.setMaximum(1.4)
        self.spin_cv.setProperty("value", 0.4)
        self.spin_cv.setObjectName("spin_cv")
        self.label_zone_4 = QtWidgets.QLabel(self.frame)
        self.label_zone_4.setGeometry(QtCore.QRect(520, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_zone_4.setFont(font)
        self.label_zone_4.setObjectName("label_zone_4")
        self.combo_cvcs = QtWidgets.QComboBox(self.frame)
        self.combo_cvcs.setGeometry(QtCore.QRect(570, 46, 41, 22))
        self.combo_cvcs.setObjectName("combo_cvcs")
        self.combo_cvcs.addItem("")
        self.combo_cvcs.addItem("")
        self.label_grunt = QtWidgets.QLabel(self.frame)
        self.label_grunt.setGeometry(QtCore.QRect(10, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_grunt.setFont(font)
        self.label_grunt.setObjectName("label_grunt")
        self.comboBox_grunt = QtWidgets.QComboBox(self.frame)
        self.comboBox_grunt.setGeometry(QtCore.QRect(182, 76, 251, 22))
        self.comboBox_grunt.setObjectName("comboBox_grunt")
        self.comboBox_grunt.addItem("")
        self.comboBox_grunt.addItem("")
        self.comboBox_grunt.addItem("")
        self.label_forest = QtWidgets.QLabel(self.frame)
        self.label_forest.setGeometry(QtCore.QRect(10, 100, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_forest.setFont(font)
        self.label_forest.setObjectName("label_forest")
        self.comboBox_forest = QtWidgets.QComboBox(self.frame)
        self.comboBox_forest.setGeometry(QtCore.QRect(250, 106, 131, 22))
        self.comboBox_forest.setObjectName("comboBox_forest")
        self.comboBox_forest.addItem("")
        self.comboBox_forest.addItem("")
        self.comboBox_forest.addItem("")
        self.label_analog = QtWidgets.QLabel(self.frame)
        self.label_analog.setGeometry(QtCore.QRect(10, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_analog.setFont(font)
        self.label_analog.setObjectName("label_analog")
        self.comboBox_analog = QtWidgets.QComboBox(self.frame)
        self.comboBox_analog.setGeometry(QtCore.QRect(200, 136, 51, 22))
        self.comboBox_analog.setObjectName("comboBox_analog")
        self.comboBox_analog.addItem("")
        self.comboBox_analog.addItem("")
        self.comboBox_analog.addItem("")
        self.label_analog_2 = QtWidgets.QLabel(self.frame)
        self.label_analog_2.setGeometry(QtCore.QRect(10, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_analog_2.setFont(font)
        self.label_analog_2.setObjectName("label_analog_2")
        self.comboBox_lake = QtWidgets.QComboBox(self.frame)
        self.comboBox_lake.setGeometry(QtCore.QRect(190, 166, 51, 22))
        self.comboBox_lake.setObjectName("comboBox_lake")
        self.comboBox_lake.addItem("")
        self.comboBox_lake.addItem("")
        self.label1_40 = QtWidgets.QLabel(self.frame)
        self.label1_40.setGeometry(QtCore.QRect(250, 167, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_40.setFont(font)
        self.label1_40.setObjectName("label1_40")
        self.spin_lsquare = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_lsquare.setGeometry(QtCore.QRect(362, 166, 62, 22))
        self.spin_lsquare.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_lsquare.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_lsquare.setMaximum(999999.0)
        self.spin_lsquare.setProperty("value", 0.0)
        self.spin_lsquare.setObjectName("spin_lsquare")
        self.label1_41 = QtWidgets.QLabel(self.frame)
        self.label1_41.setGeometry(QtCore.QRect(430, 167, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_41.setFont(font)
        self.label1_41.setObjectName("label1_41")
        self.spin_la = QtWidgets.QDoubleSpinBox(self.frame)
        self.spin_la.setGeometry(QtCore.QRect(550, 166, 62, 22))
        self.spin_la.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_la.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_la.setMaximum(999999.0)
        self.spin_la.setProperty("value", 0.0)
        self.spin_la.setObjectName("spin_la")
        self.label_analog_3 = QtWidgets.QLabel(self.frame)
        self.label_analog_3.setGeometry(QtCore.QRect(10, 190, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_analog_3.setFont(font)
        self.label_analog_3.setObjectName("label_analog_3")
        self.comboBox_swamp = QtWidgets.QComboBox(self.frame)
        self.comboBox_swamp.setGeometry(QtCore.QRect(100, 196, 331, 22))
        self.comboBox_swamp.setObjectName("comboBox_swamp")
        self.comboBox_swamp.addItem("")
        self.comboBox_swamp.addItem("")
        self.comboBox_swamp.addItem("")
        self.comboBox_swamp.addItem("")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(680, 10, 1101, 671))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.comboBox_river3 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_river3.setGeometry(QtCore.QRect(30, 190, 421, 22))
        self.comboBox_river3.setObjectName("comboBox_river3")
        self.comboBox_river2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_river2.setGeometry(QtCore.QRect(30, 150, 421, 22))
        self.comboBox_river2.setObjectName("comboBox_river2")
        self.comboBox_river1 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_river1.setGeometry(QtCore.QRect(30, 110, 421, 22))
        self.comboBox_river1.setObjectName("comboBox_river1")
        self.label_question = QtWidgets.QLabel(self.frame_2)
        self.label_question.setGeometry(QtCore.QRect(10, 10, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_question.setFont(font)
        self.label_question.setObjectName("label_question")
        self.label_square_0 = QtWidgets.QLabel(self.frame_2)
        self.label_square_0.setGeometry(QtCore.QRect(10, 33, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_square_0.setFont(font)
        self.label_square_0.setObjectName("label_square_0")
        self.spin_square_1 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spin_square_1.setGeometry(QtCore.QRect(267, 32, 62, 22))
        self.spin_square_1.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_square_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_square_1.setMaximum(999999.0)
        self.spin_square_1.setProperty("value", 0.0)
        self.spin_square_1.setObjectName("spin_square_1")
        self.label_square_1 = QtWidgets.QLabel(self.frame_2)
        self.label_square_1.setGeometry(QtCore.QRect(339, 33, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_square_1.setFont(font)
        self.label_square_1.setObjectName("label_square_1")
        self.spin_square_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spin_square_2.setGeometry(QtCore.QRect(362, 32, 62, 22))
        self.spin_square_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_square_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_square_2.setMaximum(99999999999999.0)
        self.spin_square_2.setProperty("value", 10.0)
        self.spin_square_2.setObjectName("spin_square_2")
        self.label_square_2 = QtWidgets.QLabel(self.frame_2)
        self.label_square_2.setGeometry(QtCore.QRect(430, 33, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_square_2.setFont(font)
        self.label_square_2.setObjectName("label_square_2")
        self.label_square_3 = QtWidgets.QLabel(self.frame_2)
        self.label_square_3.setGeometry(QtCore.QRect(10, 55, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_square_3.setFont(font)
        self.label_square_3.setObjectName("label_square_3")
        self.spin_square_3 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spin_square_3.setGeometry(QtCore.QRect(235, 55, 62, 22))
        self.spin_square_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_square_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_square_3.setMaximum(999999.0)
        self.spin_square_3.setProperty("value", 0.0)
        self.spin_square_3.setObjectName("spin_square_3")
        self.label_square_4 = QtWidgets.QLabel(self.frame_2)
        self.label_square_4.setGeometry(QtCore.QRect(305, 55, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_square_4.setFont(font)
        self.label_square_4.setObjectName("label_square_4")
        self.spin_square_4 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spin_square_4.setGeometry(QtCore.QRect(330, 55, 62, 22))
        self.spin_square_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_square_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_square_4.setMaximum(999999.0)
        self.spin_square_4.setProperty("value", 10.0)
        self.spin_square_4.setObjectName("spin_square_4")
        self.label_square_5 = QtWidgets.QLabel(self.frame_2)
        self.label_square_5.setGeometry(QtCore.QRect(400, 55, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_square_5.setFont(font)
        self.label_square_5.setObjectName("label_square_5")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 237, 661, 441))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.table_river1 = QtWidgets.QTableView(self.tab_4)
        self.table_river1.setGeometry(QtCore.QRect(0, 0, 661, 411))
        self.table_river1.setObjectName("table_river1")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.table_river2 = QtWidgets.QTableView(self.tab_5)
        self.table_river2.setGeometry(QtCore.QRect(0, 0, 661, 441))
        self.table_river2.setObjectName("table_river2")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.label1 = QtWidgets.QLabel(self.frame_2)
        self.label1.setGeometry(QtCore.QRect(10, 110, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.frame_2)
        self.label2.setGeometry(QtCore.QRect(10, 150, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.frame_2)
        self.label3.setGeometry(QtCore.QRect(10, 190, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(660, 0, 441, 681))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.label_question_2 = QtWidgets.QLabel(self.frame_3)
        self.label_question_2.setGeometry(QtCore.QRect(90, 10, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_question_2.setFont(font)
        self.label_question_2.setObjectName("label_question_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(0, 40, 441, 181))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.label1_16 = QtWidgets.QLabel(self.frame_5)
        self.label1_16.setGeometry(QtCore.QRect(190, 0, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_16.setFont(font)
        self.label1_16.setObjectName("label1_16")
        self.comboBox_rzone1 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_rzone1.setGeometry(QtCore.QRect(130, 28, 141, 22))
        self.comboBox_rzone1.setObjectName("comboBox_rzone1")
        self.comboBox_rzone1.addItem("")
        self.comboBox_rzone1.addItem("")
        self.label1_17 = QtWidgets.QLabel(self.frame_5)
        self.label1_17.setGeometry(QtCore.QRect(10, 30, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_17.setFont(font)
        self.label1_17.setObjectName("label1_17")
        self.label1_18 = QtWidgets.QLabel(self.frame_5)
        self.label1_18.setGeometry(QtCore.QRect(10, 60, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_18.setFont(font)
        self.label1_18.setObjectName("label1_18")
        self.comboBox_rgrunt1 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_rgrunt1.setGeometry(QtCore.QRect(180, 58, 251, 22))
        self.comboBox_rgrunt1.setObjectName("comboBox_rgrunt1")
        self.comboBox_rgrunt1.addItem("")
        self.comboBox_rgrunt1.addItem("")
        self.comboBox_rgrunt1.addItem("")
        self.label1_19 = QtWidgets.QLabel(self.frame_5)
        self.label1_19.setGeometry(QtCore.QRect(10, 90, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_19.setFont(font)
        self.label1_19.setObjectName("label1_19")
        self.comboBox_rforest1 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_rforest1.setGeometry(QtCore.QRect(250, 90, 131, 22))
        self.comboBox_rforest1.setObjectName("comboBox_rforest1")
        self.comboBox_rforest1.addItem("")
        self.comboBox_rforest1.addItem("")
        self.comboBox_rforest1.addItem("")
        self.label1_20 = QtWidgets.QLabel(self.frame_5)
        self.label1_20.setGeometry(QtCore.QRect(10, 120, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_20.setFont(font)
        self.label1_20.setObjectName("label1_20")
        self.comboBox_rlake1 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_rlake1.setGeometry(QtCore.QRect(190, 120, 51, 22))
        self.comboBox_rlake1.setObjectName("comboBox_rlake1")
        self.comboBox_rlake1.addItem("")
        self.comboBox_rlake1.addItem("")
        self.label1_21 = QtWidgets.QLabel(self.frame_5)
        self.label1_21.setGeometry(QtCore.QRect(250, 120, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_21.setFont(font)
        self.label1_21.setObjectName("label1_21")
        self.spin_lsquare1 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.spin_lsquare1.setGeometry(QtCore.QRect(360, 120, 62, 22))
        self.spin_lsquare1.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_lsquare1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_lsquare1.setMaximum(999999.0)
        self.spin_lsquare1.setProperty("value", 0.0)
        self.spin_lsquare1.setObjectName("spin_lsquare1")
        self.label1_22 = QtWidgets.QLabel(self.frame_5)
        self.label1_22.setGeometry(QtCore.QRect(10, 150, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_22.setFont(font)
        self.label1_22.setObjectName("label1_22")
        self.comboBox_rswamp1 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_rswamp1.setGeometry(QtCore.QRect(100, 150, 141, 22))
        self.comboBox_rswamp1.setObjectName("comboBox_rswamp1")
        self.comboBox_rswamp1.addItem("")
        self.comboBox_rswamp1.addItem("")
        self.comboBox_rswamp1.addItem("")
        self.comboBox_rswamp1.addItem("")
        self.label1_37 = QtWidgets.QLabel(self.frame_5)
        self.label1_37.setGeometry(QtCore.QRect(250, 150, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_37.setFont(font)
        self.label1_37.setObjectName("label1_37")
        self.spin_la1 = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.spin_la1.setGeometry(QtCore.QRect(362, 150, 62, 22))
        self.spin_la1.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_la1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_la1.setMaximum(999999.0)
        self.spin_la1.setProperty("value", 0.0)
        self.spin_la1.setObjectName("spin_la1")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(0, 220, 441, 181))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.label1_23 = QtWidgets.QLabel(self.frame_6)
        self.label1_23.setGeometry(QtCore.QRect(190, 0, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_23.setFont(font)
        self.label1_23.setObjectName("label1_23")
        self.comboBox_rzone2 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_rzone2.setGeometry(QtCore.QRect(130, 28, 141, 22))
        self.comboBox_rzone2.setObjectName("comboBox_rzone2")
        self.comboBox_rzone2.addItem("")
        self.comboBox_rzone2.addItem("")
        self.label1_24 = QtWidgets.QLabel(self.frame_6)
        self.label1_24.setGeometry(QtCore.QRect(10, 30, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_24.setFont(font)
        self.label1_24.setObjectName("label1_24")
        self.label1_25 = QtWidgets.QLabel(self.frame_6)
        self.label1_25.setGeometry(QtCore.QRect(10, 60, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_25.setFont(font)
        self.label1_25.setObjectName("label1_25")
        self.comboBox_rgrunt2 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_rgrunt2.setGeometry(QtCore.QRect(180, 58, 251, 22))
        self.comboBox_rgrunt2.setObjectName("comboBox_rgrunt2")
        self.comboBox_rgrunt2.addItem("")
        self.comboBox_rgrunt2.addItem("")
        self.comboBox_rgrunt2.addItem("")
        self.label1_26 = QtWidgets.QLabel(self.frame_6)
        self.label1_26.setGeometry(QtCore.QRect(10, 90, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_26.setFont(font)
        self.label1_26.setObjectName("label1_26")
        self.comboBox_rforest2 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_rforest2.setGeometry(QtCore.QRect(250, 90, 131, 22))
        self.comboBox_rforest2.setObjectName("comboBox_rforest2")
        self.comboBox_rforest2.addItem("")
        self.comboBox_rforest2.addItem("")
        self.comboBox_rforest2.addItem("")
        self.label1_27 = QtWidgets.QLabel(self.frame_6)
        self.label1_27.setGeometry(QtCore.QRect(10, 120, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_27.setFont(font)
        self.label1_27.setObjectName("label1_27")
        self.comboBox_rlake2 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_rlake2.setGeometry(QtCore.QRect(190, 120, 51, 22))
        self.comboBox_rlake2.setObjectName("comboBox_rlake2")
        self.comboBox_rlake2.addItem("")
        self.comboBox_rlake2.addItem("")
        self.label1_28 = QtWidgets.QLabel(self.frame_6)
        self.label1_28.setGeometry(QtCore.QRect(250, 120, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_28.setFont(font)
        self.label1_28.setObjectName("label1_28")
        self.spin_lsquare2 = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.spin_lsquare2.setGeometry(QtCore.QRect(360, 120, 62, 22))
        self.spin_lsquare2.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_lsquare2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_lsquare2.setMaximum(999999.0)
        self.spin_lsquare2.setProperty("value", 0.0)
        self.spin_lsquare2.setObjectName("spin_lsquare2")
        self.label1_29 = QtWidgets.QLabel(self.frame_6)
        self.label1_29.setGeometry(QtCore.QRect(10, 150, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_29.setFont(font)
        self.label1_29.setObjectName("label1_29")
        self.comboBox_rswamp2 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_rswamp2.setGeometry(QtCore.QRect(100, 150, 141, 22))
        self.comboBox_rswamp2.setObjectName("comboBox_rswamp2")
        self.comboBox_rswamp2.addItem("")
        self.comboBox_rswamp2.addItem("")
        self.comboBox_rswamp2.addItem("")
        self.comboBox_rswamp2.addItem("")
        self.label1_38 = QtWidgets.QLabel(self.frame_6)
        self.label1_38.setGeometry(QtCore.QRect(250, 150, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_38.setFont(font)
        self.label1_38.setObjectName("label1_38")
        self.spin_la2 = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.spin_la2.setGeometry(QtCore.QRect(362, 150, 62, 22))
        self.spin_la2.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_la2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_la2.setMaximum(999999.0)
        self.spin_la2.setProperty("value", 0.0)
        self.spin_la2.setObjectName("spin_la2")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(0, 400, 441, 181))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.label1_30 = QtWidgets.QLabel(self.frame_7)
        self.label1_30.setGeometry(QtCore.QRect(190, 0, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_30.setFont(font)
        self.label1_30.setObjectName("label1_30")
        self.comboBox_rzone3 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_rzone3.setGeometry(QtCore.QRect(130, 28, 141, 22))
        self.comboBox_rzone3.setObjectName("comboBox_rzone3")
        self.comboBox_rzone3.addItem("")
        self.comboBox_rzone3.addItem("")
        self.label1_31 = QtWidgets.QLabel(self.frame_7)
        self.label1_31.setGeometry(QtCore.QRect(10, 30, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_31.setFont(font)
        self.label1_31.setObjectName("label1_31")
        self.label1_32 = QtWidgets.QLabel(self.frame_7)
        self.label1_32.setGeometry(QtCore.QRect(10, 60, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_32.setFont(font)
        self.label1_32.setObjectName("label1_32")
        self.comboBox_rgrunt3 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_rgrunt3.setGeometry(QtCore.QRect(180, 58, 251, 22))
        self.comboBox_rgrunt3.setObjectName("comboBox_rgrunt3")
        self.comboBox_rgrunt3.addItem("")
        self.comboBox_rgrunt3.addItem("")
        self.comboBox_rgrunt3.addItem("")
        self.label1_33 = QtWidgets.QLabel(self.frame_7)
        self.label1_33.setGeometry(QtCore.QRect(10, 90, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_33.setFont(font)
        self.label1_33.setObjectName("label1_33")
        self.comboBox_rforest3 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_rforest3.setGeometry(QtCore.QRect(250, 90, 131, 22))
        self.comboBox_rforest3.setObjectName("comboBox_rforest3")
        self.comboBox_rforest3.addItem("")
        self.comboBox_rforest3.addItem("")
        self.comboBox_rforest3.addItem("")
        self.label1_34 = QtWidgets.QLabel(self.frame_7)
        self.label1_34.setGeometry(QtCore.QRect(10, 120, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_34.setFont(font)
        self.label1_34.setObjectName("label1_34")
        self.comboBox_rlake3 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_rlake3.setGeometry(QtCore.QRect(190, 120, 51, 22))
        self.comboBox_rlake3.setObjectName("comboBox_rlake3")
        self.comboBox_rlake3.addItem("")
        self.comboBox_rlake3.addItem("")
        self.label1_35 = QtWidgets.QLabel(self.frame_7)
        self.label1_35.setGeometry(QtCore.QRect(250, 120, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_35.setFont(font)
        self.label1_35.setObjectName("label1_35")
        self.spin_lsquare3 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.spin_lsquare3.setGeometry(QtCore.QRect(360, 120, 62, 22))
        self.spin_lsquare3.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_lsquare3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_lsquare3.setMaximum(999999.0)
        self.spin_lsquare3.setProperty("value", 0.0)
        self.spin_lsquare3.setObjectName("spin_lsquare3")
        self.label1_36 = QtWidgets.QLabel(self.frame_7)
        self.label1_36.setGeometry(QtCore.QRect(10, 150, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_36.setFont(font)
        self.label1_36.setObjectName("label1_36")
        self.comboBox_rswamp3 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_rswamp3.setGeometry(QtCore.QRect(100, 150, 141, 22))
        self.comboBox_rswamp3.setObjectName("comboBox_rswamp3")
        self.comboBox_rswamp3.addItem("")
        self.comboBox_rswamp3.addItem("")
        self.comboBox_rswamp3.addItem("")
        self.comboBox_rswamp3.addItem("")
        self.label1_39 = QtWidgets.QLabel(self.frame_7)
        self.label1_39.setGeometry(QtCore.QRect(250, 150, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label1_39.setFont(font)
        self.label1_39.setObjectName("label1_39")
        self.spin_la3 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.spin_la3.setGeometry(QtCore.QRect(362, 150, 62, 22))
        self.spin_la3.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_la3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_la3.setMaximum(999999.0)
        self.spin_la3.setProperty("value", 0.0)
        self.spin_la3.setObjectName("spin_la3")
        self.pushButton_clear = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_clear.setGeometry(QtCore.QRect(220, 580, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_accept = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_accept.setGeometry(QtCore.QRect(0, 580, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_accept.setFont(font)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.lineEdit_river1 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_river1.setGeometry(QtCore.QRect(460, 110, 191, 22))
        self.lineEdit_river1.setObjectName("lineEdit_river1")
        self.lineEdit_river2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_river2.setGeometry(QtCore.QRect(460, 150, 191, 22))
        self.lineEdit_river2.setObjectName("lineEdit_river2")
        self.lineEdit_river3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_river3.setGeometry(QtCore.QRect(460, 190, 191, 22))
        self.lineEdit_river3.setObjectName("lineEdit_river3")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(318, 8, 51, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_square_6 = QtWidgets.QLabel(self.frame_2)
        self.label_square_6.setGeometry(QtCore.QRect(10, 80, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_square_6.setFont(font)
        self.label_square_6.setObjectName("label_square_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1807, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.model_tablestvor2 = QtGui.QStandardItemModel()
        self.table_stvor2.setAlternatingRowColors(True)
        self.table_stvor2.setModel(self.model_tablestvor2)
        self.model_tablestvor2.setRowCount(8)
        self.model_tablestvor2.setColumnCount(15)
        self.table_stvor2.setSpan(0, 0, 1, 2)
        self.table_stvor2.setSpan(1, 0, 1, 2)
        self.table_stvor2.setSpan(2, 0, 6, 1)
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 0), 'Параметры')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 0), 'Единицы измерения')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 2), 'Q p%')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 3), 'h p%')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 4), 'u')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 5), 'b')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 6), 'b1')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 7), 'b2')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 8), 'A')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 9), 'A1')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 10), 'n')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 11), '(A + A1)^n')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 12), 'K')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 13), 'Cv')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(0, 14), 'CvCs')

        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 2), 'м^3/c')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 3), 'мм')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 4), '-')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 5), '-')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 6), '-')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 7), '-')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 8), 'км^2')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 9), 'км^2')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 10), '-')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 11), 'км^2')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 12), '-')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 13), '-')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(1, 14), '-')

        self.model_tablestvor2.setData(self.model_tablestvor2.index(2, 0), 'Расчётный створ')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(2, 1), 'P = 0.1%')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(3, 1), 'P = 1%')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(4, 1), 'P = 2%')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(5, 1), 'P = 5%')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(6, 1), 'P = 10%')
        self.model_tablestvor2.setData(self.model_tablestvor2.index(7, 1), 'P = 25%')
        self.table_stvor2.resizeColumnsToContents()
        for row in range(0, 2):
            for col in range(2, 15):
                self.model_tablestvor2.item(row, col).setEditable(False)
                self.model_tablestvor2.item(row, col).setTextAlignment(QtCore.Qt.AlignCenter)

        self.model_tableriver1 = QtGui.QStandardItemModel()
        self.model_tableriver1.setHorizontalHeaderLabels(['Характеристика', 'Единицы измерения', 'Водоём 1'])
        self.table_river1.setAlternatingRowColors(True)
        self.table_river1.setModel(self.model_tableriver1)
        self.model_tableriver1.setRowCount(9)
        self.model_tableriver1.setData(self.model_tableriver1.index(0, 0), 'Площадь водосбора')
        self.model_tableriver1.setData(self.model_tableriver1.index(1, 0), 'Залесённость')
        self.model_tableriver1.setData(self.model_tableriver1.index(2, 0), 'Заболоченность')
        self.model_tableriver1.setData(self.model_tableriver1.index(3, 0), 'Озёрность')
        self.model_tableriver1.setData(self.model_tableriver1.index(4, 0), 'Длина водотока')
        self.model_tableriver1.setData(self.model_tableriver1.index(5, 0), 'Средний уклон склонов водосбора')
        self.model_tableriver1.setData(self.model_tableriver1.index(6, 0), 'Средневзвешенный уклон русла')
        self.model_tableriver1.setData(self.model_tableriver1.index(7, 0), 'L/A^0.56')
        self.model_tableriver1.setData(self.model_tableriver1.index(8, 0), 'IxA^0.5')

        self.model_tableriver1.setData(self.model_tableriver1.index(0, 1), 'км^2')
        self.model_tableriver1.setData(self.model_tableriver1.index(1, 1), '%')
        self.model_tableriver1.setData(self.model_tableriver1.index(2, 1), '%')
        self.model_tableriver1.setData(self.model_tableriver1.index(3, 1), '%')
        self.model_tableriver1.setData(self.model_tableriver1.index(4, 1), 'км')
        self.model_tableriver1.setData(self.model_tableriver1.index(5, 1), 'Промилли')
        self.model_tableriver1.setData(self.model_tableriver1.index(6, 1), 'Промилли')
        self.model_tableriver1.setData(self.model_tableriver1.index(7, 1), '-')
        self.model_tableriver1.setData(self.model_tableriver1.index(8, 1), '-')
        for row in range(0, 9):
            for col in range(0, 2):
                self.model_tableriver1.item(row, col).setEditable(False)
                self.model_tableriver1.item(row, 1).setTextAlignment(QtCore.Qt.AlignCenter)

        self.model_tableriver2 = QtGui.QStandardItemModel()
        self.table_river2.setAlternatingRowColors(True)
        self.table_river2.setModel(self.model_tableriver2)
        self.model_tableriver2.setRowCount(20)
        self.model_tableriver2.setColumnCount(13)
        self.table_river2.setSpan(0, 0, 1, 2)
        self.table_river2.setSpan(1, 0, 1, 2)
        self.table_river2.setSpan(2, 0, 6, 1)
        self.table_river2.setSpan(8, 0, 6, 1)
        self.table_river2.setSpan(14, 0, 6, 1)
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 0), 'Параметры')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 0), 'Единицы измерения')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 2), 'Q p%')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 3), 'h p%')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 4), 'u')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 5), 'b')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 6), 'b1')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 7), 'b2')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 8), 'A')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 9), 'A1')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 10), 'n')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 11), '(A + A1)^n')
        self.model_tableriver2.setData(self.model_tableriver2.index(0, 12), 'K')

        self.model_tableriver2.setData(self.model_tableriver2.index(1, 2), 'м^3/c')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 3), 'мм')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 4), '-')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 5), '-')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 6), '-')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 7), '-')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 8), 'км^2')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 9), 'км^2')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 10), '-')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 11), 'км^2')
        self.model_tableriver2.setData(self.model_tableriver2.index(1, 12), '-')

        self.model_tableriver2.setData(self.model_tableriver2.index(2, 0), 'Водоём 1')
        self.model_tableriver2.setData(self.model_tableriver2.index(2, 1), 'P = 0.1%')
        self.model_tableriver2.setData(self.model_tableriver2.index(3, 1), 'P = 1%')
        self.model_tableriver2.setData(self.model_tableriver2.index(4, 1), 'P = 2%')
        self.model_tableriver2.setData(self.model_tableriver2.index(5, 1), 'P = 5%')
        self.model_tableriver2.setData(self.model_tableriver2.index(6, 1), 'P = 10%')
        self.model_tableriver2.setData(self.model_tableriver2.index(7, 1), 'P = 25%')

        self.model_tableriver2.setData(self.model_tableriver2.index(8, 0), 'Водоём 2')
        self.model_tableriver2.setData(self.model_tableriver2.index(8, 1), 'P = 0.1%')
        self.model_tableriver2.setData(self.model_tableriver2.index(9, 1), 'P = 1%')
        self.model_tableriver2.setData(self.model_tableriver2.index(10, 1), 'P = 2%')
        self.model_tableriver2.setData(self.model_tableriver2.index(11, 1), 'P = 5%')
        self.model_tableriver2.setData(self.model_tableriver2.index(12, 1), 'P = 10%')
        self.model_tableriver2.setData(self.model_tableriver2.index(13, 1), 'P = 25%')

        self.model_tableriver2.setData(self.model_tableriver2.index(14, 0), 'Водоём 3')
        self.model_tableriver2.setData(self.model_tableriver2.index(14, 1), 'P = 0.1%')
        self.model_tableriver2.setData(self.model_tableriver2.index(15, 1), 'P = 1%')
        self.model_tableriver2.setData(self.model_tableriver2.index(16, 1), 'P = 2%')
        self.model_tableriver2.setData(self.model_tableriver2.index(17, 1), 'P = 5%')
        self.model_tableriver2.setData(self.model_tableriver2.index(18, 1), 'P = 10%')
        self.model_tableriver2.setData(self.model_tableriver2.index(19, 1), 'P = 25%')
        self.model_tableriver2.item(0, 0).setEditable(False)
        self.model_tableriver2.item(0, 0).setTextAlignment(QtCore.Qt.AlignCenter)
        self.model_tableriver2.item(1, 0).setEditable(False)
        self.model_tableriver2.item(1, 0).setTextAlignment(QtCore.Qt.AlignCenter)
        self.model_tableriver2.item(2, 0).setEditable(False)
        self.model_tableriver2.item(2, 0).setTextAlignment(QtCore.Qt.AlignCenter)
        for row in range(8, 14):
            self.table_river2.hideRow(row)
            self.table_river2.hideRow(row + 6)
        for row in range(0, 2):
            for col in range(2, 13):
                self.model_tableriver2.item(row, col).setEditable(False)
                self.model_tableriver2.item(row, col).setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_river2.resizeColumnsToContents()

        self.spin_stvor0 = QtWidgets.QDoubleSpinBox()
        self.spin_stvor1 = QtWidgets.QDoubleSpinBox()
        self.spin_stvor2 = QtWidgets.QDoubleSpinBox()
        self.spin_stvor3 = QtWidgets.QDoubleSpinBox()
        self.spin_stvor4 = QtWidgets.QDoubleSpinBox()
        self.spin_stvor5 = QtWidgets.QDoubleSpinBox()
        self.spin_stvor6 = QtWidgets.QDoubleSpinBox()
        self.spin_stvor0.setMaximum(9999)
        self.spin_stvor4.setMaximum(999)
        self.table_stvor1.setColumnWidth(0, 260)
        self.table_stvor1.setColumnWidth(1, 170)
        for i in range(0, 7):
            self.table_stvor1.setCellWidget(i, 2, getattr(self, 'spin_stvor%s' % i))
            getattr(self, 'spin_stvor%s' % i).setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)

        self.spin_river5 = QtWidgets.QDoubleSpinBox()
        self.spin_river6 = QtWidgets.QDoubleSpinBox()
        for i in range(5, 7):
            self.table_river1.setIndexWidget(self.model_tableriver1.index(i, 2), getattr(self, 'spin_river%s' % i))
            getattr(self, 'spin_river%s' % i).setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)

        for i in range(2, 4):
            getattr(self, 'comboBox_river%s' % i).hide()
            getattr(self, 'lineEdit_river%s' % i).hide()
            getattr(self, 'label%s' % i).hide()

        self.table_river1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_river2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_stvor1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_stvor2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table_stvor1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_stvor1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_stvor1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_stvor1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.table_stvor1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.table_stvor1.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.table_stvor1.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.table_stvor1.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.table_stvor1.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.table_stvor1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Характеристика"))
        item = self.table_stvor1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Единицы измерения"))
        item = self.table_stvor1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Расчётный створ"))
        __sortingEnabled = self.table_stvor1.isSortingEnabled()
        self.table_stvor1.setSortingEnabled(False)
        item = self.table_stvor1.item(0, 0)
        item.setText(_translate("MainWindow", "Площадь водосбора"))
        item = self.table_stvor1.item(0, 1)
        item.setText(_translate("MainWindow", "км^2"))
        item = self.table_stvor1.item(1, 0)
        item.setText(_translate("MainWindow", "Залесённость"))
        item = self.table_stvor1.item(1, 1)
        item.setText(_translate("MainWindow", "%"))
        item = self.table_stvor1.item(2, 0)
        item.setText(_translate("MainWindow", "Заболоченность"))
        item = self.table_stvor1.item(2, 1)
        item.setText(_translate("MainWindow", "%"))
        item = self.table_stvor1.item(3, 0)
        item.setText(_translate("MainWindow", "Озёрность"))
        item = self.table_stvor1.item(3, 1)
        item.setText(_translate("MainWindow", "%"))
        item = self.table_stvor1.item(4, 0)
        item.setText(_translate("MainWindow", "Длина водотока"))
        item = self.table_stvor1.item(4, 1)
        item.setText(_translate("MainWindow", "км"))
        item = self.table_stvor1.item(5, 0)
        item.setText(_translate("MainWindow", "Средний уклон склонов водосбора"))
        item = self.table_stvor1.item(5, 1)
        item.setText(_translate("MainWindow", "Промилли"))
        item = self.table_stvor1.item(6, 0)
        item.setText(_translate("MainWindow", "Средневзвешенный уклон русла"))
        item = self.table_stvor1.item(6, 1)
        item.setText(_translate("MainWindow", "Промилли"))
        item = self.table_stvor1.item(7, 0)
        item.setText(_translate("MainWindow", "L/A^0.56"))
        item = self.table_stvor1.item(7, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.table_stvor1.item(8, 0)
        item.setText(_translate("MainWindow", "IxA^0.5"))
        item = self.table_stvor1.item(8, 1)
        item.setText(_translate("MainWindow", "-"))
        self.table_stvor1.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Таблица 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Таблица 2"))
        self.label_zone_2.setText(_translate("MainWindow", "Среднемноголетний слой стока вес. пол. h:"))
        self.label_zone_5.setText(_translate("MainWindow", "мм"))
        self.label_zone.setText(_translate("MainWindow", "Природная зона:"))
        self.comboBox_zone.setItemText(0, _translate("MainWindow", "Лесная и тундра"))
        self.comboBox_zone.setItemText(1, _translate("MainWindow", "Лесостепная"))
        self.label_zone_3.setText(_translate("MainWindow", "Коэффициент вариации:"))
        self.label_zone_4.setText(_translate("MainWindow", "Cv/Cs:"))
        self.combo_cvcs.setItemText(0, _translate("MainWindow", "2"))
        self.combo_cvcs.setItemText(1, _translate("MainWindow", "3"))
        self.label_grunt.setText(_translate("MainWindow", "Почвогрунты под лесом:"))
        self.comboBox_grunt.setItemText(0, _translate("MainWindow", "Супесчатые"))
        self.comboBox_grunt.setItemText(1, _translate("MainWindow", "Суглинистые"))
        self.comboBox_grunt.setItemText(2, _translate("MainWindow", "Различного механического состава"))
        self.label_forest.setText(_translate("MainWindow", "Расположение леса на водосборе:"))
        self.comboBox_forest.setItemText(0, _translate("MainWindow", "Равномерно"))
        self.comboBox_forest.setItemText(1, _translate("MainWindow", "Верхняя часть"))
        self.comboBox_forest.setItemText(2, _translate("MainWindow", "Нижняя часть"))
        self.label_analog.setText(_translate("MainWindow", "Кол-во водоёмов-аналогов:"))
        self.comboBox_analog.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_analog.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_analog.setItemText(2, _translate("MainWindow", "3"))
        self.label_analog_2.setText(_translate("MainWindow", "Наличие проточных озёр:"))
        self.comboBox_lake.setItemText(0, _translate("MainWindow", "Нет"))
        self.comboBox_lake.setItemText(1, _translate("MainWindow", "Да"))
        self.label1_40.setText(_translate("MainWindow", "Площадь озера:"))
        self.label1_41.setText(_translate("MainWindow", "A водосб. озера:"))
        self.label_analog_3.setText(_translate("MainWindow", "Тип болота:"))
        self.comboBox_swamp.setItemText(0, _translate("MainWindow", "Водосборы, включающие болота разных типов"))
        self.comboBox_swamp.setItemText(1, _translate("MainWindow", "Верховые болота на водосборах, сложенных супесчаными и легкосуглинистыми почвами (грунтами)"))
        self.comboBox_swamp.setItemText(2, _translate("MainWindow", "Низинные болота и заболоченные леса и луга на водосборах, сложенных супесчаными и легкосуглинистыми почвами (грунтами)"))
        self.comboBox_swamp.setItemText(3, _translate("MainWindow", "Верховые болота на водосборах, сложенных среднесуглинистыми и глинистыми почвами (грунтами)"))
        self.label_question.setText(_translate("MainWindow", "Показывать только рекомендованные реки"))
        self.label_square_0.setText(_translate("MainWindow", "Разброс для площади водосбора: от"))
        self.label_square_1.setText(_translate("MainWindow", "до"))
        self.label_square_2.setText(_translate("MainWindow", "км^2"))
        self.label_square_3.setText(_translate("MainWindow", "Разброс для длины водоёма: от"))
        self.label_square_4.setText(_translate("MainWindow", "до"))
        self.label_square_5.setText(_translate("MainWindow", "км"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("MainWindow", "Таблица 1"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Таблица 2"))
        self.label1.setText(_translate("MainWindow", "1"))
        self.label2.setText(_translate("MainWindow", "2"))
        self.label3.setText(_translate("MainWindow", "3"))
        self.label_question_2.setText(_translate("MainWindow", "Характеристики водоёмов-аналогов"))
        self.label1_16.setText(_translate("MainWindow", "Водоём 1"))
        self.comboBox_rzone1.setItemText(0, _translate("MainWindow", "Лесная и тундра"))
        self.comboBox_rzone1.setItemText(1, _translate("MainWindow", "Лесостепная"))
        self.label1_17.setText(_translate("MainWindow", "Природная зона"))
        self.label1_18.setText(_translate("MainWindow", "Почвогрунты под лесом"))
        self.comboBox_rgrunt1.setItemText(0, _translate("MainWindow", "Супесчатые"))
        self.comboBox_rgrunt1.setItemText(1, _translate("MainWindow", "Суглинистые"))
        self.comboBox_rgrunt1.setItemText(2, _translate("MainWindow", "Различного механического состава"))
        self.label1_19.setText(_translate("MainWindow", "Расположение леса на водосборе"))
        self.comboBox_rforest1.setItemText(0, _translate("MainWindow", "Равномерно"))
        self.comboBox_rforest1.setItemText(1, _translate("MainWindow", "Верхняя часть"))
        self.comboBox_rforest1.setItemText(2, _translate("MainWindow", "Нижняя часть"))
        self.label1_20.setText(_translate("MainWindow", "Наличие проточных озёр"))
        self.comboBox_rlake1.setItemText(0, _translate("MainWindow", "Нет"))
        self.comboBox_rlake1.setItemText(1, _translate("MainWindow", "Да"))
        self.label1_21.setText(_translate("MainWindow", "Площадь озера"))
        self.label1_22.setText(_translate("MainWindow", "Тип болота"))
        self.comboBox_rswamp1.setItemText(0, _translate("MainWindow", "Водосборы, включающие болота разных типов"))
        self.comboBox_rswamp1.setItemText(1, _translate("MainWindow", "Верховые болота на водосборах, сложенных супесчаными и легкосуглинистыми почвами (грунтами)"))
        self.comboBox_rswamp1.setItemText(2, _translate("MainWindow", "Низинные болота и заболоченные леса и луга на водосборах, сложенных супесчаными и легкосуглинистыми почвами (грунтами)"))
        self.comboBox_rswamp1.setItemText(3, _translate("MainWindow", "Верховые болота на водосборах, сложенных среднесуглинистыми и глинистыми почвами (грунтами)"))
        self.label1_37.setText(_translate("MainWindow", "A водосб. озера"))
        self.label1_23.setText(_translate("MainWindow", "Водоём 2"))
        self.comboBox_rzone2.setItemText(0, _translate("MainWindow", "Лесная и тундра"))
        self.comboBox_rzone2.setItemText(1, _translate("MainWindow", "Лесостепная"))
        self.label1_24.setText(_translate("MainWindow", "Природная зона"))
        self.label1_25.setText(_translate("MainWindow", "Почвогрунты под лесом"))
        self.comboBox_rgrunt2.setItemText(0, _translate("MainWindow", "Супесчатые"))
        self.comboBox_rgrunt2.setItemText(1, _translate("MainWindow", "Суглинистые"))
        self.comboBox_rgrunt2.setItemText(2, _translate("MainWindow", "Различного механического состава"))
        self.label1_26.setText(_translate("MainWindow", "Расположение леса на водосборе"))
        self.comboBox_rforest2.setItemText(0, _translate("MainWindow", "Равномерно"))
        self.comboBox_rforest2.setItemText(1, _translate("MainWindow", "Верхняя часть"))
        self.comboBox_rforest2.setItemText(2, _translate("MainWindow", "Нижняя часть"))
        self.label1_27.setText(_translate("MainWindow", "Наличие проточных озёр"))
        self.comboBox_rlake2.setItemText(0, _translate("MainWindow", "Нет"))
        self.comboBox_rlake2.setItemText(1, _translate("MainWindow", "Да"))
        self.label1_28.setText(_translate("MainWindow", "Площадь озера"))
        self.label1_29.setText(_translate("MainWindow", "Тип болота"))
        self.comboBox_rswamp2.setItemText(0, _translate("MainWindow", "Водосборы, включающие болота разных типов"))
        self.comboBox_rswamp2.setItemText(1, _translate("MainWindow", "Верховые болота на водосборах, сложенных супесчаными и легкосуглинистыми почвами (грунтами)"))
        self.comboBox_rswamp2.setItemText(2, _translate("MainWindow", "Низинные болота и заболоченные леса и луга на водосборах, сложенных супесчаными и легкосуглинистыми почвами (грунтами)"))
        self.comboBox_rswamp2.setItemText(3, _translate("MainWindow", "Верховые болота на водосборах, сложенных среднесуглинистыми и глинистыми почвами (грунтами)"))
        self.label1_38.setText(_translate("MainWindow", "A водосб. озера"))
        self.label1_30.setText(_translate("MainWindow", "Водоём 3"))
        self.comboBox_rzone3.setItemText(0, _translate("MainWindow", "Лесная и тундра"))
        self.comboBox_rzone3.setItemText(1, _translate("MainWindow", "Лесостепная"))
        self.label1_31.setText(_translate("MainWindow", "Природная зона"))
        self.label1_32.setText(_translate("MainWindow", "Почвогрунты под лесом"))
        self.comboBox_rgrunt3.setItemText(0, _translate("MainWindow", "Супесчатые"))
        self.comboBox_rgrunt3.setItemText(1, _translate("MainWindow", "Суглинистые"))
        self.comboBox_rgrunt3.setItemText(2, _translate("MainWindow", "Различного механического состава"))
        self.label1_33.setText(_translate("MainWindow", "Расположение леса на водосборе"))
        self.comboBox_rforest3.setItemText(0, _translate("MainWindow", "Равномерно"))
        self.comboBox_rforest3.setItemText(1, _translate("MainWindow", "Верхняя часть"))
        self.comboBox_rforest3.setItemText(2, _translate("MainWindow", "Нижняя часть"))
        self.label1_34.setText(_translate("MainWindow", "Наличие проточных озёр"))
        self.comboBox_rlake3.setItemText(0, _translate("MainWindow", "Нет"))
        self.comboBox_rlake3.setItemText(1, _translate("MainWindow", "Да"))
        self.label1_35.setText(_translate("MainWindow", "Площадь озера"))
        self.label1_36.setText(_translate("MainWindow", "Тип болота"))
        self.comboBox_rswamp3.setItemText(0, _translate("MainWindow", "Водосборы, включающие болота разных типов"))
        self.comboBox_rswamp3.setItemText(1, _translate("MainWindow", "Верховые болота на водосборах, сложенных супесчаными и легкосуглинистыми почвами (грунтами)"))
        self.comboBox_rswamp3.setItemText(2, _translate("MainWindow", "Низинные болота и заболоченные леса и луга на водосборах, сложенных супесчаными и легкосуглинистыми почвами (грунтами)"))
        self.comboBox_rswamp3.setItemText(3, _translate("MainWindow", "Верховые болота на водосборах, сложенных среднесуглинистыми и глинистыми почвами (грунтами)"))
        self.label1_39.setText(_translate("MainWindow", "A водосб. озера"))
        self.pushButton_clear.setText(_translate("MainWindow", "Очистить"))
        self.pushButton_accept.setText(_translate("MainWindow", "Рассчитать"))
        self.lineEdit_river1.setPlaceholderText(_translate("MainWindow", "Поиск по водоёмам"))
        self.lineEdit_river2.setPlaceholderText(_translate("MainWindow", "Поиск по водоёмам"))
        self.lineEdit_river3.setPlaceholderText(_translate("MainWindow", "Поиск по водоёмам"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Нет"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Да"))
        self.label_square_6.setText(_translate("MainWindow", "Водотоки-аналоги:"))
